spring.application.name=DOCTOR-MICROSERVICES
server.port=8081

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=gateway,health,info
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true
management.info.env.enabled=true
management.endpoint.gateway.enabled=true


info.app.name=Doctor Service
info.app.description=Hospital Management Doctor Microservice
info.app.version=1.0.0
info.app.owner=Hospital System



spring.datasource.url=jdbc:postgresql://localhost:5432/Hospital-Management
spring.datasource.username=postgres
spring.datasource.password=dev123



spring.jackson.deserialization.fail-on-null-for-primitives=false